//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY_MASTER
    {
        public CITY_MASTER()
        {
            this.CLIENT_MASTER = new HashSet<CLIENT_MASTER>();
            this.USER_DETAIL_MASTER = new HashSet<USER_DETAIL_MASTER>();
        }
    
        public int CITY_ID { get; set; }
        public string CITY_NAME { get; set; }
        public Nullable<int> STATE_ID { get; set; }
    
        public virtual STATE_MASTER STATE_MASTER { get; set; }
        public virtual ICollection<CLIENT_MASTER> CLIENT_MASTER { get; set; }
        public virtual ICollection<USER_DETAIL_MASTER> USER_DETAIL_MASTER { get; set; }
    }
}
