//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_MASTER
    {
        public CLIENT_MASTER()
        {
            this.CLIENTASSURANCE_MASTER = new HashSet<CLIENTASSURANCE_MASTER>();
        }
    
        public int CLIENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> AGE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> HEIGHT { get; set; }
        public string IDENTITY_OF_BODY { get; set; }
        public string ADDRESS { get; set; }
        public string PIN_CODE { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_ON { get; set; }
    
        public virtual CITY_MASTER CITY_MASTER { get; set; }
        public virtual USER_MASTER USER_MASTER { get; set; }
        public virtual ICollection<CLIENTASSURANCE_MASTER> CLIENTASSURANCE_MASTER { get; set; }
    }
}
