//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY_MASTER
    {
        public COUNTRY_MASTER()
        {
            this.STATE_MASTER = new HashSet<STATE_MASTER>();
        }
    
        public int COUNTRY_ID { get; set; }
        public string COUNTRY_NAME { get; set; }
    
        public virtual ICollection<STATE_MASTER> STATE_MASTER { get; set; }
    }
}
