//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class LIC_CMSEntities : DbContext
    {
        public LIC_CMSEntities()
            : base("name=LIC_CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITY_MASTER> CITY_MASTER { get; set; }
        public virtual DbSet<CLIENT_MASTER> CLIENT_MASTER { get; set; }
        public virtual DbSet<CLIENTASSURANCE_MASTER> CLIENTASSURANCE_MASTER { get; set; }
        public virtual DbSet<COUNTRY_MASTER> COUNTRY_MASTER { get; set; }
        public virtual DbSet<MODE_MASTER> MODE_MASTER { get; set; }
        public virtual DbSet<PLAN_MASTER> PLAN_MASTER { get; set; }
        public virtual DbSet<ROLE_MASTER> ROLE_MASTER { get; set; }
        public virtual DbSet<STATE_MASTER> STATE_MASTER { get; set; }
        public virtual DbSet<TERM_MASTER> TERM_MASTER { get; set; }
        public virtual DbSet<USER_DETAIL_MASTER> USER_DETAIL_MASTER { get; set; }
        public virtual DbSet<USER_MASTER> USER_MASTER { get; set; }
    
        public virtual int spCreateClientAssuranceMaster(Nullable<double> pREMIUM, string pOLICY_NUMBER, Nullable<double> sUM_OF_ASSURANCE, Nullable<int> pLAN_ID, Nullable<int> mODE_ID, Nullable<int> tERM_ID, Nullable<System.DateTime> dATE_OF_MATURITY, Nullable<System.DateTime> nEXT_PREMIUM_DATE, string nOMINEE, Nullable<int> cLIENT_ID, Nullable<bool> iS_ACTIVE, Nullable<bool> iS_DELETE, Nullable<int> cREATED_BY, Nullable<System.DateTime> cREATED_ON)
        {
            var pREMIUMParameter = pREMIUM.HasValue ?
                new ObjectParameter("PREMIUM", pREMIUM) :
                new ObjectParameter("PREMIUM", typeof(double));
    
            var pOLICY_NUMBERParameter = pOLICY_NUMBER != null ?
                new ObjectParameter("POLICY_NUMBER", pOLICY_NUMBER) :
                new ObjectParameter("POLICY_NUMBER", typeof(string));
    
            var sUM_OF_ASSURANCEParameter = sUM_OF_ASSURANCE.HasValue ?
                new ObjectParameter("SUM_OF_ASSURANCE", sUM_OF_ASSURANCE) :
                new ObjectParameter("SUM_OF_ASSURANCE", typeof(double));
    
            var pLAN_IDParameter = pLAN_ID.HasValue ?
                new ObjectParameter("PLAN_ID", pLAN_ID) :
                new ObjectParameter("PLAN_ID", typeof(int));
    
            var mODE_IDParameter = mODE_ID.HasValue ?
                new ObjectParameter("MODE_ID", mODE_ID) :
                new ObjectParameter("MODE_ID", typeof(int));
    
            var tERM_IDParameter = tERM_ID.HasValue ?
                new ObjectParameter("TERM_ID", tERM_ID) :
                new ObjectParameter("TERM_ID", typeof(int));
    
            var dATE_OF_MATURITYParameter = dATE_OF_MATURITY.HasValue ?
                new ObjectParameter("DATE_OF_MATURITY", dATE_OF_MATURITY) :
                new ObjectParameter("DATE_OF_MATURITY", typeof(System.DateTime));
    
            var nEXT_PREMIUM_DATEParameter = nEXT_PREMIUM_DATE.HasValue ?
                new ObjectParameter("NEXT_PREMIUM_DATE", nEXT_PREMIUM_DATE) :
                new ObjectParameter("NEXT_PREMIUM_DATE", typeof(System.DateTime));
    
            var nOMINEEParameter = nOMINEE != null ?
                new ObjectParameter("NOMINEE", nOMINEE) :
                new ObjectParameter("NOMINEE", typeof(string));
    
            var cLIENT_IDParameter = cLIENT_ID.HasValue ?
                new ObjectParameter("CLIENT_ID", cLIENT_ID) :
                new ObjectParameter("CLIENT_ID", typeof(int));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var iS_DELETEParameter = iS_DELETE.HasValue ?
                new ObjectParameter("IS_DELETE", iS_DELETE) :
                new ObjectParameter("IS_DELETE", typeof(bool));
    
            var cREATED_BYParameter = cREATED_BY.HasValue ?
                new ObjectParameter("CREATED_BY", cREATED_BY) :
                new ObjectParameter("CREATED_BY", typeof(int));
    
            var cREATED_ONParameter = cREATED_ON.HasValue ?
                new ObjectParameter("CREATED_ON", cREATED_ON) :
                new ObjectParameter("CREATED_ON", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateClientAssuranceMaster", pREMIUMParameter, pOLICY_NUMBERParameter, sUM_OF_ASSURANCEParameter, pLAN_IDParameter, mODE_IDParameter, tERM_IDParameter, dATE_OF_MATURITYParameter, nEXT_PREMIUM_DATEParameter, nOMINEEParameter, cLIENT_IDParameter, iS_ACTIVEParameter, iS_DELETEParameter, cREATED_BYParameter, cREATED_ONParameter);
        }
    
        public virtual int spCreateClientMaster(string fIRST_NAME, string lAST_NAME, string mIDDLE_NAME, Nullable<System.DateTime> dOB, Nullable<int> aGE, string mOBILE, string eMAIL, Nullable<System.DateTime> dOS, Nullable<double> wEIGHT, Nullable<double> hEIGHT, string iDENTITY_OF_BODY, string aDDRESS, string pIN_CODE, Nullable<int> cITY_ID, Nullable<long> uSER_ID, Nullable<bool> iS_ACTIVE, Nullable<bool> iS_DELETE, Nullable<int> cREATED_BY, Nullable<System.DateTime> cREATED_ON)
        {
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var mIDDLE_NAMEParameter = mIDDLE_NAME != null ?
                new ObjectParameter("MIDDLE_NAME", mIDDLE_NAME) :
                new ObjectParameter("MIDDLE_NAME", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var aGEParameter = aGE.HasValue ?
                new ObjectParameter("AGE", aGE) :
                new ObjectParameter("AGE", typeof(int));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var dOSParameter = dOS.HasValue ?
                new ObjectParameter("DOS", dOS) :
                new ObjectParameter("DOS", typeof(System.DateTime));
    
            var wEIGHTParameter = wEIGHT.HasValue ?
                new ObjectParameter("WEIGHT", wEIGHT) :
                new ObjectParameter("WEIGHT", typeof(double));
    
            var hEIGHTParameter = hEIGHT.HasValue ?
                new ObjectParameter("HEIGHT", hEIGHT) :
                new ObjectParameter("HEIGHT", typeof(double));
    
            var iDENTITY_OF_BODYParameter = iDENTITY_OF_BODY != null ?
                new ObjectParameter("IDENTITY_OF_BODY", iDENTITY_OF_BODY) :
                new ObjectParameter("IDENTITY_OF_BODY", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var pIN_CODEParameter = pIN_CODE != null ?
                new ObjectParameter("PIN_CODE", pIN_CODE) :
                new ObjectParameter("PIN_CODE", typeof(string));
    
            var cITY_IDParameter = cITY_ID.HasValue ?
                new ObjectParameter("CITY_ID", cITY_ID) :
                new ObjectParameter("CITY_ID", typeof(int));
    
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(long));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var iS_DELETEParameter = iS_DELETE.HasValue ?
                new ObjectParameter("IS_DELETE", iS_DELETE) :
                new ObjectParameter("IS_DELETE", typeof(bool));
    
            var cREATED_BYParameter = cREATED_BY.HasValue ?
                new ObjectParameter("CREATED_BY", cREATED_BY) :
                new ObjectParameter("CREATED_BY", typeof(int));
    
            var cREATED_ONParameter = cREATED_ON.HasValue ?
                new ObjectParameter("CREATED_ON", cREATED_ON) :
                new ObjectParameter("CREATED_ON", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateClientMaster", fIRST_NAMEParameter, lAST_NAMEParameter, mIDDLE_NAMEParameter, dOBParameter, aGEParameter, mOBILEParameter, eMAILParameter, dOSParameter, wEIGHTParameter, hEIGHTParameter, iDENTITY_OF_BODYParameter, aDDRESSParameter, pIN_CODEParameter, cITY_IDParameter, uSER_IDParameter, iS_ACTIVEParameter, iS_DELETEParameter, cREATED_BYParameter, cREATED_ONParameter);
        }
    
        public virtual ObjectResult<spGetClientAssuranceMaster_Result> spGetClientAssuranceMaster(Nullable<int> cLIENTASSURANCE_ID)
        {
            var cLIENTASSURANCE_IDParameter = cLIENTASSURANCE_ID.HasValue ?
                new ObjectParameter("CLIENTASSURANCE_ID", cLIENTASSURANCE_ID) :
                new ObjectParameter("CLIENTASSURANCE_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetClientAssuranceMaster_Result>("spGetClientAssuranceMaster", cLIENTASSURANCE_IDParameter);
        }
    
        public virtual int spUpdateClientAssuranceMaster(Nullable<int> cLIENTASSURANCE_ID, Nullable<double> pREMIUM, string pOLICY_NUMBER, Nullable<double> sUM_OF_ASSURANCE, Nullable<int> pLAN_ID, Nullable<int> mODE_ID, Nullable<int> tERM_ID, Nullable<System.DateTime> dATE_OF_MATURITY, Nullable<System.DateTime> nEXT_PREMIUM_DATE, string nOMINEE, Nullable<int> cLIENT_ID, Nullable<bool> iS_ACTIVE, Nullable<bool> iS_DELETE, Nullable<int> uPDATED_BY, Nullable<System.DateTime> uPDATE_ON)
        {
            var cLIENTASSURANCE_IDParameter = cLIENTASSURANCE_ID.HasValue ?
                new ObjectParameter("CLIENTASSURANCE_ID", cLIENTASSURANCE_ID) :
                new ObjectParameter("CLIENTASSURANCE_ID", typeof(int));
    
            var pREMIUMParameter = pREMIUM.HasValue ?
                new ObjectParameter("PREMIUM", pREMIUM) :
                new ObjectParameter("PREMIUM", typeof(double));
    
            var pOLICY_NUMBERParameter = pOLICY_NUMBER != null ?
                new ObjectParameter("POLICY_NUMBER", pOLICY_NUMBER) :
                new ObjectParameter("POLICY_NUMBER", typeof(string));
    
            var sUM_OF_ASSURANCEParameter = sUM_OF_ASSURANCE.HasValue ?
                new ObjectParameter("SUM_OF_ASSURANCE", sUM_OF_ASSURANCE) :
                new ObjectParameter("SUM_OF_ASSURANCE", typeof(double));
    
            var pLAN_IDParameter = pLAN_ID.HasValue ?
                new ObjectParameter("PLAN_ID", pLAN_ID) :
                new ObjectParameter("PLAN_ID", typeof(int));
    
            var mODE_IDParameter = mODE_ID.HasValue ?
                new ObjectParameter("MODE_ID", mODE_ID) :
                new ObjectParameter("MODE_ID", typeof(int));
    
            var tERM_IDParameter = tERM_ID.HasValue ?
                new ObjectParameter("TERM_ID", tERM_ID) :
                new ObjectParameter("TERM_ID", typeof(int));
    
            var dATE_OF_MATURITYParameter = dATE_OF_MATURITY.HasValue ?
                new ObjectParameter("DATE_OF_MATURITY", dATE_OF_MATURITY) :
                new ObjectParameter("DATE_OF_MATURITY", typeof(System.DateTime));
    
            var nEXT_PREMIUM_DATEParameter = nEXT_PREMIUM_DATE.HasValue ?
                new ObjectParameter("NEXT_PREMIUM_DATE", nEXT_PREMIUM_DATE) :
                new ObjectParameter("NEXT_PREMIUM_DATE", typeof(System.DateTime));
    
            var nOMINEEParameter = nOMINEE != null ?
                new ObjectParameter("NOMINEE", nOMINEE) :
                new ObjectParameter("NOMINEE", typeof(string));
    
            var cLIENT_IDParameter = cLIENT_ID.HasValue ?
                new ObjectParameter("CLIENT_ID", cLIENT_ID) :
                new ObjectParameter("CLIENT_ID", typeof(int));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var iS_DELETEParameter = iS_DELETE.HasValue ?
                new ObjectParameter("IS_DELETE", iS_DELETE) :
                new ObjectParameter("IS_DELETE", typeof(bool));
    
            var uPDATED_BYParameter = uPDATED_BY.HasValue ?
                new ObjectParameter("UPDATED_BY", uPDATED_BY) :
                new ObjectParameter("UPDATED_BY", typeof(int));
    
            var uPDATE_ONParameter = uPDATE_ON.HasValue ?
                new ObjectParameter("UPDATE_ON", uPDATE_ON) :
                new ObjectParameter("UPDATE_ON", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateClientAssuranceMaster", cLIENTASSURANCE_IDParameter, pREMIUMParameter, pOLICY_NUMBERParameter, sUM_OF_ASSURANCEParameter, pLAN_IDParameter, mODE_IDParameter, tERM_IDParameter, dATE_OF_MATURITYParameter, nEXT_PREMIUM_DATEParameter, nOMINEEParameter, cLIENT_IDParameter, iS_ACTIVEParameter, iS_DELETEParameter, uPDATED_BYParameter, uPDATE_ONParameter);
        }
    
        public virtual int spUpdateClientMaster(Nullable<int> cLIENT_ID, string fIRST_NAME, string lAST_NAME, string mIDDLE_NAME, Nullable<System.DateTime> dOB, Nullable<int> aGE, string mOBILE, string eMAIL, Nullable<System.DateTime> dOS, Nullable<double> wEIGHT, Nullable<double> hEIGHT, string iDENTITY_OF_BODY, string aDDRESS, string pIN_CODE, Nullable<int> cITY_ID, Nullable<long> uSER_ID, Nullable<bool> iS_ACTIVE, Nullable<bool> iS_DELETE, Nullable<int> uPDATED_BY, Nullable<System.DateTime> uPDATE_ON)
        {
            var cLIENT_IDParameter = cLIENT_ID.HasValue ?
                new ObjectParameter("CLIENT_ID", cLIENT_ID) :
                new ObjectParameter("CLIENT_ID", typeof(int));
    
            var fIRST_NAMEParameter = fIRST_NAME != null ?
                new ObjectParameter("FIRST_NAME", fIRST_NAME) :
                new ObjectParameter("FIRST_NAME", typeof(string));
    
            var lAST_NAMEParameter = lAST_NAME != null ?
                new ObjectParameter("LAST_NAME", lAST_NAME) :
                new ObjectParameter("LAST_NAME", typeof(string));
    
            var mIDDLE_NAMEParameter = mIDDLE_NAME != null ?
                new ObjectParameter("MIDDLE_NAME", mIDDLE_NAME) :
                new ObjectParameter("MIDDLE_NAME", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var aGEParameter = aGE.HasValue ?
                new ObjectParameter("AGE", aGE) :
                new ObjectParameter("AGE", typeof(int));
    
            var mOBILEParameter = mOBILE != null ?
                new ObjectParameter("MOBILE", mOBILE) :
                new ObjectParameter("MOBILE", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var dOSParameter = dOS.HasValue ?
                new ObjectParameter("DOS", dOS) :
                new ObjectParameter("DOS", typeof(System.DateTime));
    
            var wEIGHTParameter = wEIGHT.HasValue ?
                new ObjectParameter("WEIGHT", wEIGHT) :
                new ObjectParameter("WEIGHT", typeof(double));
    
            var hEIGHTParameter = hEIGHT.HasValue ?
                new ObjectParameter("HEIGHT", hEIGHT) :
                new ObjectParameter("HEIGHT", typeof(double));
    
            var iDENTITY_OF_BODYParameter = iDENTITY_OF_BODY != null ?
                new ObjectParameter("IDENTITY_OF_BODY", iDENTITY_OF_BODY) :
                new ObjectParameter("IDENTITY_OF_BODY", typeof(string));
    
            var aDDRESSParameter = aDDRESS != null ?
                new ObjectParameter("ADDRESS", aDDRESS) :
                new ObjectParameter("ADDRESS", typeof(string));
    
            var pIN_CODEParameter = pIN_CODE != null ?
                new ObjectParameter("PIN_CODE", pIN_CODE) :
                new ObjectParameter("PIN_CODE", typeof(string));
    
            var cITY_IDParameter = cITY_ID.HasValue ?
                new ObjectParameter("CITY_ID", cITY_ID) :
                new ObjectParameter("CITY_ID", typeof(int));
    
            var uSER_IDParameter = uSER_ID.HasValue ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(long));
    
            var iS_ACTIVEParameter = iS_ACTIVE.HasValue ?
                new ObjectParameter("IS_ACTIVE", iS_ACTIVE) :
                new ObjectParameter("IS_ACTIVE", typeof(bool));
    
            var iS_DELETEParameter = iS_DELETE.HasValue ?
                new ObjectParameter("IS_DELETE", iS_DELETE) :
                new ObjectParameter("IS_DELETE", typeof(bool));
    
            var uPDATED_BYParameter = uPDATED_BY.HasValue ?
                new ObjectParameter("UPDATED_BY", uPDATED_BY) :
                new ObjectParameter("UPDATED_BY", typeof(int));
    
            var uPDATE_ONParameter = uPDATE_ON.HasValue ?
                new ObjectParameter("UPDATE_ON", uPDATE_ON) :
                new ObjectParameter("UPDATE_ON", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateClientMaster", cLIENT_IDParameter, fIRST_NAMEParameter, lAST_NAMEParameter, mIDDLE_NAMEParameter, dOBParameter, aGEParameter, mOBILEParameter, eMAILParameter, dOSParameter, wEIGHTParameter, hEIGHTParameter, iDENTITY_OF_BODYParameter, aDDRESSParameter, pIN_CODEParameter, cITY_IDParameter, uSER_IDParameter, iS_ACTIVEParameter, iS_DELETEParameter, uPDATED_BYParameter, uPDATE_ONParameter);
        }
    
        public virtual ObjectResult<spGetClientMaster_Result5> spGetClientMaster(Nullable<int> cLIENT_ID)
        {
            var cLIENT_IDParameter = cLIENT_ID.HasValue ?
                new ObjectParameter("CLIENT_ID", cLIENT_ID) :
                new ObjectParameter("CLIENT_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetClientMaster_Result5>("spGetClientMaster", cLIENT_IDParameter);
        }
    }
}
