//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_MASTER
    {
        public int ROLE_ID { get; set; }
        public string ROLE_ABBR { get; set; }
        public string ROLE_NAME { get; set; }
        public Nullable<int> IS_ACTIE { get; set; }
    }
}
