//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    
    public partial class spGetClientMaster_Result1
    {
        public int CLIENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> NEXT_PREMIUM_DATE { get; set; }
        public string POLICY_NUMBER { get; set; }
        public Nullable<double> PREMIUM { get; set; }
        public Nullable<double> SUM_OF_ASSURANCE { get; set; }
        public Nullable<System.DateTime> DATE_OF_MATURITY { get; set; }
    }
}
