//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    
    public partial class spGetClientMaster_Result5
    {
        public int CLIENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> AGE { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<double> WEIGHT { get; set; }
        public Nullable<double> HEIGHT { get; set; }
        public string IDENTITY_OF_BODY { get; set; }
        public string ADDRESS { get; set; }
        public string PIN_CODE { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public int CLIENTASSURANCE_ID { get; set; }
        public Nullable<double> PREMIUM { get; set; }
        public string POLICY_NUMBER { get; set; }
        public Nullable<int> PLAN_ID { get; set; }
        public Nullable<int> MODE_ID { get; set; }
        public Nullable<int> TERM_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_MATURITY { get; set; }
        public Nullable<System.DateTime> NEXT_PREMIUM_DATE { get; set; }
        public Nullable<double> SUM_OF_ASSURANCE { get; set; }
        public string NOMINEE { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
    }
}
