//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE_MASTER
    {
        public STATE_MASTER()
        {
            this.CITY_MASTER = new HashSet<CITY_MASTER>();
        }
    
        public int STATE_ID { get; set; }
        public string STATE_NAME { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
    
        public virtual ICollection<CITY_MASTER> CITY_MASTER { get; set; }
        public virtual COUNTRY_MASTER COUNTRY_MASTER { get; set; }
    }
}
