//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIC_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DETAIL_MASTER
    {
        public int USER_DETAIL_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string PIN_CODE { get; set; }
        public string AGENT_CODE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
    
        public virtual CITY_MASTER CITY_MASTER { get; set; }
        public virtual USER_MASTER USER_MASTER { get; set; }
    }
}
